server:
  port: 8888

spring:
  application:
    name: location-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lincolngithub/location/
          searchPaths: location-config/config-client-dev.properties
          label: master